SUPERUSER = "SuperUser"
FRANCHISE_USER = "FranchiseUser"
MANAGER_USER = "ManagerUser"
EMPLOYEE_USER = "EmployeeUser"

SYSTEM_ROLES = {SUPERUSER, FRANCHISE_USER, MANAGER_USER, EMPLOYEE_USER}
STAFF_SELF_SERVICE_ROLES = {MANAGER_USER, EMPLOYEE_USER}
